### PR TITLE
Prevent make clean from failing when the file to remove does not exist

### PR DESCRIPTION
**Pull request by Quintasan**
Well, I never realized I would change something here but with my maintainer hat on I can fully say I don't want my package to fail building on make clean.

Could you make a release with this change so I can package that for Debian/Ubuntu?

### CODE REVIEW

**Comment by Quintasan** [comment]
Or hell, even scratch this and just make a release. just realized the tarball has old Makefile.

**Comment by hanschen** [comment]
I'll try to make a new release as soon as I can, probably tomorrow if I can find the time. Thanks for the heads up and for packaging ksuperkey!

**Comment by Mehanik** [comment]
Also you can use my repository for Ubuntu: https://launchpad.net/~mehanik/+archive/ubuntu/ksuperkey

**Comment by hanschen** [comment]
I've made a new release over at KDE-apps: http://kde-apps.org/content/show.php/ksuperkey?content=154569

Just to make sure I understood your comment correctly, the `-f` flag is not necessary (i.e., I can close this pull request), correct?

**Comment by Quintasan** [comment]
Yeah sure, the existence test seems like an overkill here since you can just rm -f the file and it will not exit with an error when the file does not exist. But don't fix what's not broken :)

**Comment by hanschen** [comment]
Thanks for confirming, please let me know if there are any other packaging issues.

**Pull request closed without merging**
